### ISSUE TITLE
Dying on a raid utterly destroys my body

### ISSUE THREAD

**Issue by Agoelia** [TGWeaver/CDDA-Sky-Islands#21]
![123](https://user-images.githubusercontent.com/13697781/215279497-f2630037-35f7-409d-9edd-03cfd36a15b2.PNG)

There is no coming back from this. It takes several irl seconds to move a single tile, hours to do anything in-game, I'm blind, can't wield anything, I can't even craft a Quickheal (meaning I miraculously have the shards on hand, but I literally cannot craft)

Please reduce the amount of damage one receives when dying. 
Even better, when one dies, teleport them back home as they are, and heal just enough to bring them to life. 
My arms where fine when I died, why are they so damaged now?

**Comment by Agoelia** [comment]
Update: 
Used the debug feature to spawn in a quickheal, and ate it. 
My feet, hands, mouth and eyes are all still broken.

**Comment by TGWeaver** [comment]
This is the same as issue #18 .
To summarize: Death itself is what reduces all parts to 0 hp, and this is hardcoded. Sub-limbs normally don't heal OR receive damage, but death will break them. And finally while this didn't used to be a problem, a very new CDDA patch changed it so that my healing code no longer affects sub-limbs.

Solution: download a version of CDDA from a few days ago, or wait until this bug is patched out in the main branch.
